### ISSUE TITLE
IndentationError: flatbuffer_reader.py : 272

### ISSUE THREAD

**Issue by milinddeore** [PeteBlackerThe3rd/tflite_analyser#1]
I think for now `reorder_execution` is None, hence `Lazy` must be `pass`.

**Comment by PeteBlackerThe3rd** [comment]
Thanks for the heads up. I accidentally pushed a broken version to the repo. I've just pushed the latest version of my code up now to fix this. You can see the updated [code here](https://github.com/PeteBlackerThe3rd/tflite_analyser/blob/master/flatbuffer_reader.py#L302).

I'm closing this now it's been fixed by [this commit ](https://github.com/PeteBlackerThe3rd/tflite_analyser/commit/210b57d9c0e85fa7c4cccdea4dbd2733e0443f22)
